In [67]:
import numpy as np 
import matplotlib.pyplot as plt 

In [68]:
def Returns(alpha, stock_returns):
    
    '''
    Dimensions: 

    alpha = [N, T]
    stock_returns = [N, T]
    
    '''

    N, T = alpha.shape 
    Portfolio_Daily_Returns = np.zeros((T))
    alpha = alpha.transpose()
    stock_returns = stock_returns.transpose()
    
    for i in range(T):

        Portfolio_Daily_Returns[i] = np.dot(alpha[i], stock_returns[i])
    
    return Portfolio_Daily_Returns

In [69]:
def Variance(alpha, stock_returns):
    
    '''
    Dimensions: 

    alpha = [N, T]
    stock_returns = [N, T]
    
    '''
    
    N, T = alpha.shape 
    Portfolio_Daily_Variance = np.ones((T))
    alpha = alpha.transpose()
    stock_returns = stock_returns.transpose()
    
    for i in range(T):
         
        #print (np.cov(stock_returns[i], ddof = 1))    
        print ((stock_returns[i])) 
        Portfolio_Daily_Variance[i] = np.dot(np.multiply(alpha[i], np.cov(stock_returns[i], ddof = 1)), alpha[i].transpose())
        
        
    print (Portfolio_Daily_Variance)
    return Portfolio_Daily_Variance
        

In [70]:
def Sharpe(alpha, stock_returns, r = 0.0):

    '''
    Dimensions: 

    alpha = [N, T]
    stock_returns = [N, T]
    
    '''

    Portfolio_Daily_Returns = Returns(alpha, stock_returns)
    Portfolio_Daily_Variance = Variance(alpha, stock_returns)
    Portfolio_Daily_Sharpe = (Portfolio_Daily_Returns - r)/np.sqrt(Portfolio_Daily_Variance)
    
    return Portfolio_Daily_Sharpe

In [71]:

alpha = np.ones((4, 5)) * 0.25
stock_returns =  np.arange(20).reshape(4,5)

Daily_Sharpe = Sharpe(alpha, stock_returns)
print (Daily_Sharpe)



[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]
[10.41666667 10.41666667 10.41666667 10.41666667 10.41666667]
[2.32379001 2.63362868 2.94346734 3.25330601 3.56314468]
